### ISSUE TITLE
built-in pages should support '/' shortcut to go to search box.

### ISSUE THREAD

**Issue by hanwen** [google/zoekt#109]

**Comment by dziemba** [comment]
Hey @hanwen, I saw that you implemented this in https://github.com/google/zoekt/commit/983e877dba55963e63ebabb4af4a2e5b8d7a2f03

It's a cool feature! Unfortunately it breaks entering the `/` character in the search box. That's because the event handler catches all key presses, even when entering text into the text field, and then stops the event chain. 

I have not tried this, but maybe it's already enough to change the `return false` to `return true` in the handler function, so that the event keeps propagating.

**Comment by hanwen** [comment]
that kind of works, but then it puts '/' in the search box too .  I guess I have to 'return false' only if search box is not in focus.

**Comment by hanwen** [comment]
https://gerrit-review.googlesource.com/c/zoekt/+/271555

**Comment by dziemba** [comment]
Looks good, thanks! :+1:
